services:
  worker:
    build: ./worker
    env_file:
      - ./worker/.env
      #for linux , because by default host.docker.internal is not resolved
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import psycopg2; c=psycopg2.connect('${DATABASE_URL}'); c.close()"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s